deployment:
  tasks:
    - export DEPLOYPATH=/home6/pgroup/public_html
    - /bin/cp admin.html $DEPLOYPATH
    - /bin/cp create-partner.html $DEPLOYPATH
    - /bin/cp create-work.html $DEPLOYPATH
    - /bin/cp get-all-partners.html $DEPLOYPATH
    - /bin/cp get-all-works.html $DEPLOYPATH
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp send_email.php $DEPLOYPATH
    - /bin/cp -r public $DEPLOYPATH
    - /bin/cp composer.json $DEPLOYPATH
    - /bin/cp composer.lock $DEPLOYPATH